modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="custom_chat" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Custom Chat" #mandatory
logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
credits="Custom Chat" #optional
# A text field displayed in the mod UI
authors="Girogio2103" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Custom Chat.
'''
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
